from aiogram.utils.emoji import emojize


class Emojis:
    NONE = None
    karma = emojize(':airplane:')
    rules = emojize(':scroll:')
    hi = emojize(':person_raising_hand:')
    luggage = emojize(':luggage:')
    box = emojize(':package:')
    buy = emojize(':magnifying_glass_tilted_left:')
    sell = emojize(':man_tipping_hand:')
    label = emojize(':label:')
    delivery = emojize(':person_running:')
    wardrobe = emojize(':necktie:')
    anonymous = emojize(':new_moon_face:')
    baraholka = emojize(':yarn:')
    web_link = emojize(':globe_with_meridians:')
    description = emojize(':page_with_curl:')
    price = emojize(':money_bag:')
    question = emojize(':white_question_mark:')

    ads = emojize(':coin:')
    in_parking = emojize(':right_arrow_curving_down: :P_button:')
    out_parking = emojize(':right_arrow_curving_up: :P_button:')

    in_gates = emojize(':right_arrow: :house:')
    out_gates = emojize(':house: :right_arrow:')

    garden = emojize(":deciduous_tree:")
    entrance = emojize(":classical_building:")

    next = emojize(':right_arrow:')
    next_finger = emojize(':backhand_index_pointing_right:')
    folder_img = emojize(':file_folder:')
    back = emojize(':left_arrow:')
    stop_auction = emojize(':stop_button:')
    money = emojize(':coin:')
    edit = "✏"
    go = "➜"

    add = emojize(':plus:')
    mail = emojize(':envelope_with_arrow:')
    message_commentary = emojize(':envelope:')
    verify_property = emojize(':check_mark:')
    make_favourite = emojize(':glowing_star:')
    remove = emojize(':cross_mark:')
    text_type = emojize(':memo:')
    photo_type = emojize(':camera:')
    yes_fav = emojize(':green_circle:')
    not_now = emojize(':hourglass_not_done:')
    access = emojize(':speech_balloon:')
    shield = emojize(':shield:')
    ohrana = emojize(':sport_utility_vehicle:') + emojize(':delivery_truck:')
    call_center = emojize(':telephone:')
    razgruzka = emojize(':delivery_truck:')
    services = emojize(':shopping_bags:')
    support_dev = emojize(':red_heart: :folded_hands:')
    like_bot = emojize(':smiling_face:')
    support_coffee = emojize(':hot_beverage:')
    info = emojize(':information:')
    alarm = emojize(':police_car_light:')
    no_alarm = emojize(':face_with_hand_over_mouth:')
    entrance_pass = emojize(':key:')
    menu = emojize(':house:')
    razgruzka_parking = emojize(':P_button:')
    adminka = emojize(':man_tipping_hand:')
    mail_service = emojize(':closed_mailbox_with_raised_flag:')
    qr = emojize(':pager:')
    properties = emojize(':castle:')
    premium = emojize(':glowing_star:')
    credit_card = emojize(':credit_card:')
    warning = emojize(':red_exclamation_mark:')
    favourite_account = emojize(':star:')
    cancel_registration = emojize(':hollow_red_circle:')
    phone = emojize(':telephone_receiver:')
    warn = emojize(":double_exclamation_mark:")
    propusk = emojize(':automobile:')
    chat = emojize(':key:')
    approve = emojize(':check_mark_button:')
    decline = emojize(':prohibited:')
    kill = emojize(':water_pistol:')
    waiting = emojize(':speech_balloon:')
    change_house = emojize(':counterclockwise_arrows_button:')
    update = emojize(':TOP_arrow:')
    turn_off = emojize(':bell_with_slash:')
    authorize_by_id = emojize(':ticket:')
    continue_button = emojize(':fast-forward_button:')
    clocks = emojize(':two-thirty:')
    assistant = emojize(':man_police_officer:')
    phone_is_down = emojize(':backhand_index_pointing_down:') * 3
    is_up = emojize(':backhand_index_pointing_up:') * 3
