---
name: 'deploy dobrobot to dokku'

on:
  push:
    branches:
      - dobrobot

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'main'
          git_remote_url: ${{ env.REMOTE_URL_DOBROBOT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host_key: ${{ secrets.SSH_HOST_KEY }}
