name: Deploy to Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Dokku
        uses: appleboy/ssh-action@master
        with:
          dokku-host: 46.101.228.44
          dokku-ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-app-name: vas3kanon
          args: |
            git push dokku main:master
