---
name: 'deploy to dokku'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.REMOTE_URL_ANON }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Push to dobrobot
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.REMOTE_URL_DOBROBOT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}